const functionalMenu = new Array();

functionalMenu.push({ id: "01", name: "Functional.booleanSupplier()", path: "functional-boolean-supplier" });
functionalMenu.push({ id: "02", name: "Functional.intSupplier()", path: "functional-int-supplier" });
functionalMenu.push({ id: "03", name: "Functional.intConsumer()", path: "functional-int-consumer" });
functionalMenu.push({ id: "04", name: "Functional.intPredicate()", path: "functional-int-predicate" });
functionalMenu.push({ id: "05", name: "Functional.intToLongFunction()", path: "functional-int-to-long-function" });
functionalMenu.push({ id: "06", name: "Functional.intToDoubleFunction()", path: "functional-int-to-double-function" });
functionalMenu.push({ id: "07", name: "Functional.intBinaryOperator()", path: "functional-int-binary-operator" });
functionalMenu.push({ id: "08", name: "Functional.intUnaryOperator()", path: "functional-int-unary-operator" });
functionalMenu.push({ id: "09", name: "Functional.longSupplier()", path: "functional-long-supplier" });
functionalMenu.push({ id: "10", name: "Functional.longConsumer()", path: "functional-long-consumer" });
functionalMenu.push({ id: "11", name: "Functional.longPredicate()", path: "functional-long-predicate" });
functionalMenu.push({ id: "12", name: "Functional.longToIntFunction()", path: "functional-long-to-int-function" });
functionalMenu.push({ id: "13", name: "Functional.longToDoubleFunction()", path: "functional-long-to-double-function" });
functionalMenu.push({ id: "14", name: "Functional.longBinaryOperator()", path: "functional-long-binary-operator" });
functionalMenu.push({ id: "15", name: "Functional.longUnaryOperator()", path: "functional-long-unary-operator" });
functionalMenu.push({ id: "16", name: "Functional.doubleSupplier()", path: "functional-double-supplier" });
functionalMenu.push({ id: "17", name: "Functional.doubleConsumer()", path: "functional-double-consumer" });
functionalMenu.push({ id: "18", name: "Functional.doublePredicate()", path: "functional-double-predicate" });
functionalMenu.push({ id: "19", name: "Functional.doubleToIntFunction()", path: "functional-double-to-int-function" });
functionalMenu.push({ id: "20", name: "Functional.doubleToLongFunction()", path: "functional-double-to-long-function" });
functionalMenu.push({ id: "21", name: "Functional.doubleBinaryOperator()", path: "functional-double-binary-operator" });
functionalMenu.push({ id: "22", name: "Functional.doubleUnaryOperator()", path: "functional-double-unary-operator" });
functionalMenu.push({ id: "23", name: "Functional.supplier()", path: "functional-supplier" });
functionalMenu.push({ id: "24", name: "Functional.consumer()", path: "functional-consumer" });
functionalMenu.push({ id: "25", name: "Functional.predicate()", path: "functional-predicate" });
functionalMenu.push({ id: "26", name: "Functional.function()", path: "functional-function" });
functionalMenu.push({ id: "27", name: "Functional.biConsumer()", path: "functional-bi-consumer" });
functionalMenu.push({ id: "28", name: "Functional.biPredicate()", path: "functional-bi-predicate" });
functionalMenu.push({ id: "29", name: "Functional.biFunction()", path: "functional-bi-function" });
functionalMenu.push({ id: "30", name: "Functional.binaryOperator()", path: "functional-binary-operator" });
functionalMenu.push({ id: "31", name: "Functional.toIntFunction()", path: "functional-to-int-function" });
functionalMenu.push({ id: "32", name: "Functional.toLongFunction()", path: "functional-to-long-function" });
functionalMenu.push({ id: "33", name: "Functional.toDoubleFunction()", path: "functional-to-double-function" });
functionalMenu.push({ id: "34", name: "Functional.toIntBiFunction()", path: "functional-to-int-bi-function" });
functionalMenu.push({ id: "35", name: "Functional.toLongBiFunction()", path: "functional-to-long-bi-function" });
functionalMenu.push({ id: "36", name: "Functional.toDoubleBiFunction()", path: "functional-to-double-bi-function" });
functionalMenu.push({ id: "37", name: "Functional.intFunction()", path: "functional-int-function" });
functionalMenu.push({ id: "38", name: "Functional.longFunction()", path: "functional-long-function" });
functionalMenu.push({ id: "39", name: "Functional.doubleFunction()", path: "functional-double-function" });
functionalMenu.push({ id: "40", name: "Functional.objIntConsumer()", path: "functional-obj-int-consumer" });
functionalMenu.push({ id: "41", name: "Functional.objLongConsumer()", path: "functional-obj-long-consumer" });
functionalMenu.push({ id: "42", name: "Functional.objDoubleConsumer()", path: "functional-obj-double-consumer" });
functionalMenu.push({ id: "43", name: "Functional.unaryOperator()", path: "functional-unary-operator" });
functionalMenu.push({ id: "44", name: "Functional.comparator()", path: "functional-comparator" });

loadMenu(document.getElementById("functional-menu"), functionalMenu);
